### ISSUE TITLE
Resubmit jobs too many times?

### ISSUE THREAD

**Issue by mtmorgan** [mtmorgan/RedisParam#7]
@Jiefei-Wang 
 it seems like this will resubmit the job perhaps many times https://github.com/mtmorgan/RedisParam/blob/bb37176b55538a78b2edfbd4f3a0ca128a60e8b5/R/RedisBackend-class.R#L112 perhaps if workers are slow to respond?

**Comment by Jiefei-Wang** [comment]
Hi Martin, I think this issue is solved. Would you be able to close this issue?(I do not have the permission to do it)
